# MiniBatchKMeans

In [26]:
import pandas as pd
import numpy as np
from sklearn.cluster import MiniBatchKMeans

Es conveniente utilizar `MiniBatchKMeans` si contamos con una decente cantidad de poder de c√≥mputo pero no con mucha memoria RAM.

In [4]:
dataset = pd.read_csv('data/candy.csv')
dataset.head(5)

,competitorname,chocolate,fruity,caramel,peanutyalmondy,nougat,crispedricewafer,hard,bar,pluribus,sugarpercent,pricepercent,winpercent
0,100 Grand,1,0,1,0,0,1,0,1,0,0.732,0.860,66.971725
1,3 Musketeers,1,0,0,0,1,0,0,1,0,0.604,0.511,67.602936
2,One dime,0,0,0,0,0,0,0,0,0,0.011,0.116,32.261086
3,One quarter,0,0,0,0,0,0,0,0,0,0.011,0.511,46.116505
4,Air Heads,0,1,0,0,0,0,0,0,0,0.906,0.511,52.341465

In [6]:
X = dataset.drop(columns=['competitorname'])

In [13]:
import os

In [16]:
os.environ['OMP_NUM_THREADS'] = "1"

In [27]:
kmeans = MiniBatchKMeans(n_clusters=4)
kmeans.fit(X)
pred = kmeans.predict(X)
print("Prediction \n" + "-"*16)
print(pred)
print(np.unique(kmeans.labels_))

c:\Users\Cesar\.conda\envs\ds\lib\site-packages\sklearn\cluster\_kmeans.py:1043: UserWarning: MiniBatchKMeans is known to have a memory leak on Windows with MKL, when there are less chunks than available threads. You can prevent it by setting batch_size >= 4096 or by setting the environment variable OMP_NUM_THREADS=1
  warnings.warn(

Prediction
----------------
[0 0 1 2 2 2 2 1 1 1 1 1 1 1 1 1 1 2 2 1 2 1 2 0 2 0 1 2 3 1 1 2 3 0 2 2 3
 0 0 2 2 2 3 0 1 1 2 0 1 1 1 3 3 3 3 1 0 1 1 1 0 2 1 2 3 0 0 2 0 1 1 1 1 2
 2 1 2 2 2 3 2 1 2 1 2]
[0 1 2 3]

In [29]:
X['group'] = pred
X.head()

,chocolate,fruity,caramel,peanutyalmondy,nougat,crispedricewafer,hard,bar,pluribus,sugarpercent,pricepercent,winpercent,group
0,1,0,1,0,0,1,0,1,0,0.732,0.860,66.971725,0
1,1,0,0,0,1,0,0,1,0,0.604,0.511,67.602936,0
2,0,0,0,0,0,0,0,0,0,0.011,0.116,32.261086,1
3,0,0,0,0,0,0,0,0,0,0.011,0.511,46.116505,2
4,0,1,0,0,0,0,0,0,0,0.906,0.511,52.341465,2